### ISSUE TITLE
Default value for parameter is not set

### ISSUE THREAD

**Issue by sven-ahrens** [nahakiole/staruml-php#2]
**Default value for operation parameters are not set after code generation**
Operation parameters can't have a default value, as it'll not be set after code generation

**Attach the .mdj file**
.mdj files are not supported which is why I embed two screenshots

**To Reproduce**
1. Create a class diagram
2. Create a class
3. Add an operation to the class
4. Add a parameter to the operation
5. Click on the parameter to configure
6. Go under "Properties"
7. Write down a type related value under "defaultValue"

**Expected behavior**
1. Code should be generated
2. Parameter has a default value

**Actual behavior**
1. Parameter has no default value

**Screenshots**
<img width="350" alt="Bildschirmfoto 2019-03-28 um 23 02 30" src="https://user-images.githubusercontent.com/18313443/55196000-64dee780-51ae-11e9-8940-65dcee021d45.png">
<img width="403" alt="Bildschirmfoto 2019-03-28 um 23 02 52" src="https://user-images.githubusercontent.com/18313443/55196004-65777e00-51ae-11e9-83b7-4f54349b5d77.png">

**Comment by nahakiole** [comment]
Thank you for reporting the bug, I fixed it with https://github.com/nahakiole/staruml-php/commit/80ff72cbad8f2ce73798e96656ebe8e6bb8598f8 and I'll try to release 0.0.2 today which will include the bugfix.
